
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Copyright>Creative Commons</Copyright>
    <Company>Swordfish Computing Pty Ltd</Company>
    <Product>Swordfish.NET.TestV3</Product>
    <Title>Swordfish.NET.UnitTestV3</Title>
    <Version>1.0.0</Version>
    <AssemblyOriginatorKeyFile>Swordfish.NET.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="System.ValueTuple" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Swordfish.NET.CollectionsV3\Swordfish.NET.CollectionsV3.csproj" />
  </ItemGroup>
</Project>